include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

stages:
￼    - flatpak

variables:
    BUNDLE: "info.febvre.Komikku.flatpak"

flatpak:
    image: 'registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:3.34'
    stage: flatpak
    variables:
        MANIFEST_PATH: "flatpak/info.febvre.Komikku.json"
        MESON_ARGS: "-Dprofile=development"
        FLATPAK_MODULE: "komikku"
        RUNTIME_REPO: "https://flathub.org/repo/flathub.flatpakrepo"
        APP_ID: "info.febvre.Komikku"
    extends: .flatpak

review:
    stage: deploy
    dependencies:
        - 'flatpak'
    extends: '.review'

stop_review:
    stage: deploy
    extends: '.stop_review'
